/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file .dev.vars.example --include-runtime=false` (hash: cb568335c8e293b1e97097b4d466e13d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		QUIZ_TTL_SECONDS: "300";
		SUPABASE_URL: "https://hezknmxwxsiqhyjerhpl.supabase.co";
		QUIZ_IMAGE_BASE_URL: "https://raw.githubusercontent.com/hodadako/blog/main";
		QUIZ_TOKEN_SECRET: string;
		COMMENT_AUTHORIZATION_SECRET: string;
		SUPABASE_SERVICE_ROLE_KEY: string;
		IP_HASH_SECRET: string;
		INVITE_TOKEN_PEPPER: string;
		COMMENT_PASSWORD_PEPPER: string;
		ADMIN_API_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "QUIZ_TTL_SECONDS" | "SUPABASE_URL" | "QUIZ_IMAGE_BASE_URL" | "QUIZ_TOKEN_SECRET" | "COMMENT_AUTHORIZATION_SECRET" | "SUPABASE_SERVICE_ROLE_KEY" | "IP_HASH_SECRET" | "INVITE_TOKEN_PEPPER" | "COMMENT_PASSWORD_PEPPER" | "ADMIN_API_SECRET">> {}
}
