/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file .dev.vars.example --include-runtime=false` (hash: 48a01f6172c8ba7aa0fdc59652acabd5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		QUIZ_TTL_SECONDS: "300";
		QUIZ_TOKEN_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "QUIZ_TTL_SECONDS" | "QUIZ_TOKEN_SECRET">> {}
}
